version: "3.9"

services:
  web:
    image: ${DOCKERHUB_USERNAME}/mjsec-boj:${IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: suika_game.settings
      PORT: 8000
    volumes:
      - static_volume:/app/staticfiles
    depends_on: []

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx:/etc/nginx/templates
      - certbot_config:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    environment:
      DOMAIN: ${DOMAIN}

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_config:/etc/letsencrypt
      - certbot_www:/var/www/certbot

volumes:
  static_volume:
  certbot_config:
  certbot_www:
